Vagrant.configure("2") do |config|
  config.vm.synced_folder "/mnt/c/vagrant", "/vagrant"
  config.vm.box = "ubuntu/focal64"
  config.vm.boot_timeout = 1200
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
  end
  config.vm.define "guest1" do |guest|
    guest.vm.network "private_network", ip: "192.168.56.20"
  end
  config.vm.define "guest2" do |guest|
    guest.vm.network "private_network", ip: "192.168.56.30"
  end
end